// ============================================================
// glosario.js — Diccionario del analista (guía de aprendizaje)
// ============================================================

export const GLOSARIO = {
  "SOC": { def: "Security Operations Center. El equipo que monitoriza y responde a incidentes de seguridad 24/7." },
  // ---- Red team (pentest ofensivo) ----
  "Footprinting": { def: "Recopilación de información de un objetivo (DNS, IPs, correos, tecnología) antes de atacar." },
  "Enumeración": { def: "Fase del pentest que descubre servicios, usuarios, directorios y versiones de un sistema." },
  "CVE": { def: "Common Vulnerabilities and Exposures. Identificador público de una vulnerabilidad conocida." },
  "OSINT": { def: "Open Source Intelligence. Inteligencia obtenida de fuentes públicas: buscadores, redes sociales, registros DNS." },
  "Fuerza bruta": { def: "Ataque que prueba todas las combinaciones posibles (o un diccionario) para adivinar credenciales." },
  "Diccionario": { def: "Lista de passwords comunes usada para atacar credenciales. Un top-1000 vence a la mayoría de los humanos." },
  "MFA": { def: "Multi-Factor Authentication. Verificación con dos o más factores (algo que sabes, tienes y eres)." },
  "fail2ban": { def: "Herramienta que bloquea IPs tras varios intentos de login fallidos. Básica en SSH expuesto." },
  "SQLi": { def: "SQL Injection. Vulnerabilidad que permite manipular consultas SQL mediante parámetros sin validar." },
  "Prepared statements": { def: "Consultas SQL parametrizadas que separan el código de los datos: la defensa definitiva contra SQLi." },
  "Sal (salt)": { def: "Dato aleatorio añadido a una password antes de hashearla. Evita que hashes iguales revelen passwords iguales." },
  "WAF": { def: "Web Application Firewall. Filtro que analiza el tráfico HTTP para bloquear ataques a aplicaciones web." },
  "RCE": { def: "Remote Code Execution. Ejecución de código arbitrario en un sistema remoto: el sueño de todo atacante." },
  "Meterpreter": { def: "Payload avanzado de Metasploit que da una sesión interactiva y modular en el sistema comprometido." },
  "sudoers": { def: "Archivo que define qué usuarios pueden ejecutar qué comandos con sudo. Mal configurado = escalada regalada." },
  "NOPASSWD": { def: "Directiva de sudoers que permite ejecutar un comando como root sin pedir password. Peligrosa con binarios abusables." },
  "LSASS": { def: "Proceso de Windows que guarda credenciales en memoria. Mimikatz las extrae de ahí." },
  "NTLM": { def: "Protocolo/hash de autenticación de Windows. Los hashes NTLM robados permiten ataques pass-the-hash." },
  "Pivote": { def: "Usar un sistema comprometido como trampolín para alcanzar otros a los que no se llega directamente." },
  "Credential Guard": { def: "Función de Windows que aísla LSASS en un entorno virtualizado, dificultando la extracción de credenciales." },
  "Informe ejecutivo": { def: "Resumen del pentest orientado a dirección: riesgo de negocio, hallazgos clave y recomendaciones." },
  "Crown jewels": { def: "Los activos más valiosos de una organización: bases de clientes, propiedad intelectual, cuentas maestras." },
  "DLP": { def: "Data Loss Prevention. Sistemas que detectan y bloquean la salida de datos sensibles de la red." },
  "RGPD": { def: "Reglamento General de Protección de Datos. Normativa europea que obliga a proteger los datos personales." },
  "CSIRT": { def: "Computer Security Incident Response Team. Equipo de respuesta a incidentes de alto nivel." },
  "Phishing": { def: "Ataque de ingeniería social que suplanta a una entidad de confianza para robar credenciales o instalar malware." },
  "Spear phishing": { def: "Phishing dirigido a una persona u organización concreta, usando información personalizada para parecer legítimo." },
  "BEC": { def: "Business Email Compromise. Fraude que suplanta a directivos/proveedores para ordenar transferencias o pagos falsos." },
  "Ingeniería social": { def: "Manipulación psicológica para que la víctima revele datos o realice acciones que comprometen la seguridad." },
  "SPF": { def: "Sender Policy Framework. Registro DNS que indica qué servidores pueden enviar correo por un dominio." },
  "DKIM": { def: "DomainKeys Identified Mail. Firma criptográfica del correo que permite verificar su autenticidad." },
  "DMARC": { def: "Domain-based Message Authentication Reporting. Política que dice qué hacer con correos que fallan SPF/DKIM." },
  "Lookalike": { def: "Dominio que imita visualmente a uno legítimo (acme-facturas.info vs acme.com). Técnica típica de phishing." },
  "Macro": { def: "Código (VBA) embebido en documentos de Office. Los atacantes lo usan para descargar malware al abrir el archivo." },
  "RAT": { def: "Remote Access Trojan. Malware que da control remoto del equipo infectado al atacante." },
  "IOC": { def: "Indicator of Compromise. Evidencia de intrusión: dominios, IPs, hashes, URLs, comportamientos." },
  "Ransomware": { def: "Malware que cifra los archivos de la víctima y exige un rescate para devolverlos." },
  "Rescate": { def: "Pago exigido por el ransomware. No se paga: sin garantía de descifrado, y financia la siguiente campaña." },
  "VSS": { def: "Volume Shadow Copy: copias de sombra de Windows. El ransomware las borra con vssadmin para impedir la restauración local." },
  "C2": { def: "Command & Control. Infraestructura del atacante para controlar los equipos infectados." },
  "Copias de sombra": { def: "Snapshot del sistema Windows usado para recuperar archivos. El ransomware las borra para impedir la recuperación." },
  "Living Off the Land": { def: "Técnica de usar herramientas legítimas del sistema (PowerShell, WMI, mshta) para pasar desapercibido." },
  "Beaconing": { def: "Comunicación periódica de un malware con su C2. Patrón detectable por regularidad." },
  "Movimiento lateral": { def: "Fase del ataque donde el intruso se desplaza por la red usando credenciales robadas buscando datos valiosos." },
  "Fuerza bruta": { def: "Ataque que prueba miles de contraseñas hasta acertar. Se mitiga con bloqueo de cuenta, MFA y VPN." },
  "Mimikatz": { def: "Herramienta de post-explotación que extrae credenciales y hashes de la memoria del sistema." },
  "Credential dumping": { def: "Robo de credenciales almacenadas en memoria o disco (SAM, LSASS, navegadores)." },
  "MFA": { def: "Multi-Factor Authentication. Segundo factor de autenticación que bloquea el acceso aunque roben la contraseña." },
  "RDP": { def: "Remote Desktop Protocol. Escritorio remoto de Windows; expuesto a Internet es un imán para fuerza bruta." },
  "Persistencia": { def: "Mecanismo del atacante para mantenerse en el sistema tras reinicios (tareas programadas, servicios, registros)." },
  "Túnel DNS": { def: "Técnica de exfiltración que esconde datos en consultas DNS (subdominios), canal que casi nadie monitoriza." },
  "Exfiltración": { def: "Salida no autorizada de datos de la organización hacia el exterior." },
  "Entropía": { def: "Medida de aleatoriedad de una cadena. Subdominios con alta entropía = señal de túnel DNS." },
  "Cuenta de servicio": { def: "Cuenta usada por aplicaciones/servicios, no por personas. Suele tener privilegios y poca vigilancia." },
  "RGPD": { def: "Reglamento General de Protección de Datos. Obliga a notificar brechas de datos personales en 72 horas." },
  "TXT record": { def: "Registro DNS de texto libre. Usado por túneles DNS para transportar datos exfiltrados." },
  "Falso positivo": { def: "Alerta que parece un ataque pero no lo es. El triaje correcto lo detecta sin interrumpir la operación." },
  "Baseline": { def: "Línea base de comportamiento normal de la red. Las desviaciones se miden contra ella." },
  "DLP": { def: "Data Loss Prevention. Tecnología que monitoriza y bloquea la salida de datos sensibles." },
  "Triaje": { def: "Primera clasificación de una alerta: ¿es incidente, falso positivo o ruido? Decisión clave del SOC." },
  "SLA": { def: "Service Level Agreement. Tiempo máximo para responder a un incidente según su severidad." },
  "EDR": { def: "Endpoint Detection and Response. Sensor en los equipos que detecta y responde a comportamientos maliciosos." },
  "SIEM": { def: "Security Information and Event Management. Plataforma que centraliza logs y correlaciona alertas." },
  "VT": { def: "VirusTotal. Servicio que analiza archivos y URLs con múltiples antivirus." },
  "MITRE ATT&CK": { def: "Base de conocimiento de tácticas y técnicas de ataque. El lenguaje común de los equipos de seguridad." },
  "Hash": { def: "Huella digital de un archivo (MD5, SHA-256). Sirve para identificar malware de forma inequívoca." },
  "Whois": { def: "Consulta de registro de un dominio o IP: titular, fechas, servidores DNS. Clave para validar indicadores." },
  "Triage": { def: "Versión inglesa de triaje: priorizar y clasificar alertas en función del riesgo." },
};
